name: Review App

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Scotty
        uses: factorial-io/scotty-deploy-action@v1
        with:
          scotty-server: ${{ secrets.SCOTTY_SERVER }}
          scotty-token: ${{ secrets.SCOTTY_TOKEN }}
          app-name: myapp-pr-${{ github.event.pull_request.number }}
          service: web:80
          ttl: 7d
          destroy-on-ttl: true

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Review app deployed: ${{ steps.deploy.outputs.app-url }}'
            })

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Destroy review app
        uses: factorial-io/scotty-deploy-action@v1
        with:
          scotty-server: ${{ secrets.SCOTTY_SERVER }}
          scotty-token: ${{ secrets.SCOTTY_TOKEN }}
          app-name: myapp-pr-${{ github.event.pull_request.number }}
          action: destroy
